### ISSUE TITLE
Whitescreen "of death" on Linux

### ISSUE THREAD

**Issue by med4u** [Storj/storjshare-gui#317]
### Versions

- **GUI Version:** v1.0.3
- **Operating System:** Linux mint 17.3

### Expected Behavior

```
Show the UI working properly more than few hours :)
```

### Actual Behavior

I installed all betas before (test group B) with .deb and it worked very well.

But after few hours of running, I have those whitescreens since few releases (can't remember exactly since when)!
So I tried to : Installed it with git clone and npm and it launch, but same bug again.
Even with loglevel off on both options (deb and npm) it crashes.

I have 3 drives on share.

Logs and proper functioning seems stopped at the moment of the bug... And no response, only a whitescreen.
I can use the function reload (in View menu, Ctrl+R), but after few hours it freeze again with the whitescreen

```
Logs are available at : https://cestquoi.fr/owncloud/index.php/s/nLXuLSfkXVdeIJA
```

### Screenshots (Optional)

![storj_bug](https://cloud.githubusercontent.com/assets/19374726/17247792/03a3c164-5596-11e6-8d8d-93af9568cac8.png)

Thank you for this huge project! Keep the good work going on!
Hope to get this work on every platform :)
If you need more info, ask, I will run the commands you ask ;)

**Comment by DaSpawn** [comment]
I am seeing this also, and it also appears the share drives stop running when it is doing this.  I have to exit and restart to regain functionality, but even then the interface is very slugish/unresponsive untill I restart my computer

**Comment by bookchin** [comment]
This will get resolved with #259 and https://github.com/Storj/core/issues/143

**Comment by RedRockMining** [comment]
Still having WSoD error using Storj Share 1.0.3 Core Library 2.0.7 Protocol 0.7.1 on Windows 10 with no logging. If it helps, it seems to take longer now maybe 2 or 3 days vs. 24 hours previously, but still happens with 100% certainty.

**Comment by RedRockMining** [comment]
Update: WSD again. This time however I noticed that memory usage after StorjShare stopped was only 55 MB. Previously I believe this issue was thought to have been the result of too much log information begin posted. This appears to not be the case now.

**Comment by super3** [comment]
@RedRockMining https://github.com/Storj/core/issues/143 will be closed with https://github.com/Storj/core/pull/423.

**Comment by super3** [comment]
@RedRockMining @DaSpawn Storj/core#143 will be closed with Storj/core#423. Feel free to help test when its we have a pre-release version next week.
